#@ load("@ytt:data", "data")

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: #@ data.values.clusterRoleBindingName
subjects:
- kind: ServiceAccount
  name: #@ data.values.serviceAccountName
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

 